name: Auto Complete Release (Changesets 🦋)

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    if: |
      github.event.pull_request.head.ref == 'changeset-release/main' &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Merge Immediately if Allowed
        run: gh pr merge --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}