name: PR Checks

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Type check
        run: |
          if grep -q "\"typecheck\":" package.json; then
            pnpm typecheck
          else
            echo "No typecheck script found, skipping"
          fi
        
      - name: Lint
        run: |
          if grep -q "\"lint\":" package.json; then
            pnpm lint
          else
            echo "No lint script found, skipping"
          fi
        
      - name: Test
        run: |
          if grep -q "\"test\":" package.json; then
            pnpm test
          else
            echo "No test script found, skipping"

      - name: Build
        run: |
          if grep -q "\"build\":" package.json; then
            pnpm build
          else
            echo "No build script found, skipping"
          fi

      